hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

dropbox_login:
    pattern: /login/check-dropbox

uco_consigna:
    resource: "@UcoConsignaBundle/Controller/"
    type:     annotation
    prefix:   /

