security:
    encoders:
        Uco\ConsignaBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        dropbox_hwi_provider:
            id: dropbox.oauth_user_provider.service

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern: ^/
            anonymous: true
            logout:
                path:   /logout
                target: /
            oauth:
                resource_owners:
                    dropbox:      "/login/check-dropbox"
                login_path:       /login
                failure_path:     /login
                oauth_user_provider:
                    service:  dropbox.oauth_user_provider.service

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
