security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern: ^/
            logout:       true
            anonymous:    true
            oauth:
                resource_owners:
                    dropbox:      "/login/check-dropbox"
                login_path:       /connect/dropbox
                failure_path:     /
                oauth_user_provider:
                    service:  dropbox.oauth_user_provider.service

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile$, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/job, role: ROLE_ADMIN }
        - { path: ^/process, role: IS_AUTHENTICATED_ANONYMOUSLY }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN