<?php
/**
 * Created by PhpStorm.
 * User: sergio
 * Date: 20/11/13
 * Time: 13:05
 */

namespace Uco\ConsignaBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends EntityRepository
{
}